os: linux
language: python
matrix:
  include:
  - dist: bionic
    python: 2.7
  - dist: xenial
    python: 3.4
  - dist: xenial
    python: 3.5
  - dist: bionic
    python: 3.6
  - dist: bionic
    python: 3.7
install:
  - pip install coverage
  - pip install .
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Avoid ssh "known hosts" warnings
  - printf '%s\n    %s\n    %s\n' 'Host *' 'StrictHostKeyChecking no' 'LogLevel ERROR' >> ~/.ssh/config
  # ssh: propagate TRAVIS* environment variables
  - printf '    %s\n' 'SendEnv TRAVIS*' >> ~/.ssh/config
  - sudo sh -c "echo 'AcceptEnv TRAVIS*' >> /etc/ssh/sshd_config"
  - sudo service ssh restart
  # Activate virtualenv when sshing to localhost to enable gateway tests
  - sed -i "1isource $VIRTUAL_ENV/bin/activate" ~/.bashrc
  # WorkerPdsh
  - sudo apt-get -y install pdsh
  - sudo sh -c 'echo ssh > /etc/pdsh/rcmd_default'
script:
  - nosetests -v --all-modules --with-coverage --cover-tests --cover-erase --cover-package=ClusterShell tests
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: R9Hwy5oshH4zIjl03WjaFiUGTvh6A7bfU/RvMjTfofwC9o7Jc5cCC6trr7DK/ryq+LwKInhnuIEFFFWkODw7wk60bJqGrotG7Dfvx+6/GbKEgoM78VEqWPR4ylUMfYLUh3qhGxAd40whxE4RUpQ0x8OdsRxZqT/ZVfzsq+DVtQo=
